"""Update Default Purchase Order template to clean A4 layout, fix 'line' undefined.

Revision ID: 020_po_template_a4
Revises: 019_doc_tpl_wysiwyg
Create Date: 2026-02-23

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import text

revision: str = "020_po_template_a4"
down_revision: Union[str, None] = "019_doc_tpl_wysiwyg"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Template body (HTML inside <body>)
PO_TEMPLATE_BODY = """
<div class="row" style="align-items:flex-start;">
  <div>
    <div class="title">Chartwell Press</div>
    <div class="muted">Purchase Order</div>
  </div>
  <div class="box" style="min-width: 260px;">
    <div><strong>PO No:</strong> {{ po.po_number if po.po_number and not po.po_number.startswith('DRAFT-') else 'Draft' }}</div>
    <div><strong>Order date:</strong> {{ po.order_date.strftime('%d/%m/%Y') if po.order_date else '' }}</div>
    {% if po.required_by %}<div><strong>Required by:</strong> {{ po.required_by.strftime('%d/%m/%Y') }}</div>{% endif %}
    {% if po.expected_by %}<div><strong>Expected by:</strong> {{ po.expected_by.strftime('%d/%m/%Y') }}</div>{% endif %}
  </div>
</div>

<div class="row" style="margin-top: 14px;">
  <div class="box" style="flex:1;">
    <div style="font-weight:700; margin-bottom: 6px;">Supplier</div>
    <div>{{ supplier.name if supplier else po.supplier_id }}</div>
    {% if supplier and supplier.address %}<div class="muted">{{ supplier.address }}</div>{% endif %}
    {% if supplier and supplier.city %}<div class="muted">{{ supplier.city }}</div>{% endif %}
    {% if supplier and supplier.postcode %}<div class="muted">{{ supplier.postcode }}</div>{% endif %}
    {% if supplier and supplier.country %}<div class="muted">{{ supplier.country }}</div>{% endif %}
    {% if supplier and supplier.email %}<div class="muted">{{ supplier.email }}</div>{% endif %}
    {% if supplier and supplier.phone %}<div class="muted">{{ supplier.phone }}</div>{% endif %}
  </div>
  <div class="box" style="flex:1;">
    <div style="font-weight:700; margin-bottom: 6px;">Delivery</div>
    {% if po.delivery_name %}<div>{{ po.delivery_name }}</div>{% endif %}
    {% if po.delivery_address %}<div class="muted">{{ po.delivery_address }}</div>{% endif %}
  </div>
</div>

{% if po.notes %}
  <div class="box" style="margin-top: 14px;">
    <div style="font-weight:700; margin-bottom: 6px;">Notes</div>
    <div>{{ po.notes }}</div>
  </div>
{% endif %}

<table class="po-lines" role="table" aria-label="Purchase order lines">
  <thead>
    <tr>
      <th class="c-desc">Description</th>
      <th class="c-code">Supplier code</th>
      <th class="c-qty">Qty</th>
      <th class="c-uom">UOM</th>
      <th class="c-unit">Unit cost</th>
      <th class="c-total">Line total</th>
    </tr>
  </thead>
  <tbody>
    {% if lines and (lines|length) > 0 %}
      {% for line in lines %}
        <tr>
          <td class="c-desc">
            <div class="desc-main">{{ line.description or '—' }}</div>
          </td>
          <td class="c-code">{{ line.supplier_product_code or '—' }}</td>
          <td class="c-qty">{{ '%.2f'|format(line.qty or 0) }}</td>
          <td class="c-uom">{{ line.uom or '—' }}</td>
          <td class="c-unit">£{{ '%.2f'|format(line.unit_cost_gbp or 0) }}</td>
          <td class="c-total">£{{ '%.2f'|format(line.line_total_gbp or 0) }}</td>
        </tr>
      {% endfor %}
    {% else %}
      <tr>
        <td colspan="6" class="no-lines">No lines</td>
      </tr>
    {% endif %}
  </tbody>
</table>

<table class="po-totals" role="table" aria-label="Totals">
  <tbody>
    <tr><td>Subtotal</td><td>£{{ '%.2f'|format(po.subtotal_gbp or 0) }}</td></tr>
    <tr><td>VAT</td><td>£{{ '%.2f'|format(po.vat_gbp or 0) }}</td></tr>
    <tr class="grand"><td>Total</td><td>£{{ '%.2f'|format(po.total_gbp or 0) }}</td></tr>
  </tbody>
</table>

<div class="footer">
  Generated by Chartwell Press · Please quote PO number on all correspondence.
</div>
"""

# Custom CSS for A4 print
PO_TEMPLATE_CSS = """@page { size: A4; margin: 14mm; }
body { font-family: Arial, Helvetica, sans-serif; font-size: 12px; color: #111; }
h1,h2,h3 { margin: 0; }
.row { display: flex; justify-content: space-between; gap: 18px; }
.muted { color: #666; }
.title { font-size: 20px; font-weight: 700; letter-spacing: 0.5px; }
.box { border: 1px solid #ddd; padding: 10px 12px; border-radius: 8px; }
.po-lines {
  width: 100%;
  border-collapse: collapse;
  margin-top: 14px;
  font-size: 12px;
}
.po-lines thead th {
  text-align: left;
  padding: 8px 8px;
  border-bottom: 2px solid #111;
  font-weight: 700;
  letter-spacing: 0.2px;
}
.po-lines tbody td {
  padding: 8px 8px;
  border-bottom: 1px solid #ddd;
  vertical-align: top;
}
.po-lines .c-qty,
.po-lines .c-unit,
.po-lines .c-total {
  text-align: right;
  white-space: nowrap;
}
.po-lines .c-code,
.po-lines .c-uom {
  white-space: nowrap;
}
.po-lines .c-desc { width: 48%; }
.po-lines .c-code { width: 16%; }
.po-lines .c-qty  { width: 8%; }
.po-lines .c-uom  { width: 8%; }
.po-lines .c-unit { width: 10%; }
.po-lines .c-total{ width: 10%; }
.po-lines .desc-main { font-weight: 600; }
.po-lines .desc-sub { margin-top: 3px; color: #555; font-size: 11px; }
.po-lines .no-lines { text-align: center; padding: 14px 8px; color: #666; }

.po-totals {
  width: 40%;
  margin-left: auto;
  margin-top: 12px;
  border-collapse: collapse;
  font-size: 12px;
}
.po-totals td {
  padding: 6px 8px;
  border-bottom: 1px solid #ddd;
}
.po-totals td:last-child {
  text-align: right;
  white-space: nowrap;
}
.po-totals .grand td {
  border-bottom: 2px solid #111;
  font-weight: 800;
}
.footer { margin-top: 18px; font-size: 11px; color: #666; }
"""


def upgrade() -> None:
    conn = op.get_bind()
    # Update Default Purchase Order template (by id or by name)
    conn.execute(
        text("""
            UPDATE document_templates
            SET template_html = :body, template_css = :css
            WHERE doc_type = 'purchase_order'
              AND (id = '0808d8fb-5d50-4ad0-b5e1-4b88d082f3ad' OR name = 'Default Purchase Order')
        """),
        {"body": PO_TEMPLATE_BODY, "css": PO_TEMPLATE_CSS},
    )


def downgrade() -> None:
    # Revert to legacy content-only (clear template_html/css so content is used)
    conn = op.get_bind()
    conn.execute(
        text("""
            UPDATE document_templates
            SET template_html = NULL, template_css = NULL
            WHERE doc_type = 'purchase_order' AND name = 'Default Purchase Order'
        """),
    )
