"""Update active PO template to clean A4 structured layout.

Revision ID: 022_po_a4_structured
Revises: 021_po_template_amp
Create Date: 2026-02-23

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import text

revision: str = "022_po_a4_structured"
down_revision: Union[str, None] = "021_po_template_amp"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Jinja-safe: use 'and' not &, fallback with or, all {{ line.* }} inside {% for %}
PO_TEMPLATE_BODY = """
<header class="po-header">
  <div class="po-header-left">
    <h1 class="po-title">Purchase Order</h1>
    <div class="company">Chartwell Press</div>
  </div>
  <div class="po-header-right">
    <div><strong>PO No:</strong> {{ po.po_number if po.po_number and not po.po_number.startswith('DRAFT-') else 'Draft' }}</div>
    <div><strong>Order date:</strong> {{ po.order_date.strftime('%d/%m/%Y') if po.order_date else '' }}</div>
    {% if po.required_by %}<div><strong>Required by:</strong> {{ po.required_by.strftime('%d/%m/%Y') }}</div>{% endif %}
    {% if po.expected_by %}<div><strong>Expected by:</strong> {{ po.expected_by.strftime('%d/%m/%Y') }}</div>{% endif %}
  </div>
</header>

<div class="po-addresses">
  <div class="po-box">
    <div class="po-box-title">Supplier</div>
    <div>{{ supplier.name if supplier else po.supplier_id }}</div>
    {% if supplier and supplier.address %}<div class="muted">{{ supplier.address }}</div>{% endif %}
    {% if supplier and supplier.city %}<div class="muted">{{ supplier.city }}</div>{% endif %}
    {% if supplier and supplier.postcode %}<div class="muted">{{ supplier.postcode }}</div>{% endif %}
    {% if supplier and supplier.country %}<div class="muted">{{ supplier.country }}</div>{% endif %}
    {% if supplier and supplier.email %}<div class="muted">{{ supplier.email }}</div>{% endif %}
    {% if supplier and supplier.phone %}<div class="muted">{{ supplier.phone }}</div>{% endif %}
  </div>
  <div class="po-box">
    <div class="po-box-title">Delivery</div>
    {% if po.delivery_name %}<div>{{ po.delivery_name }}</div>{% endif %}
    {% if po.delivery_address %}<div class="muted">{{ po.delivery_address }}</div>{% endif %}
  </div>
</div>

{% if po.notes %}
<div class="po-notes">
  <div class="po-box-title">Notes</div>
  <div>{{ po.notes }}</div>
</div>
{% endif %}

<table class="po-lines" role="table" aria-label="Purchase order lines">
  <thead>
    <tr>
      <th class="c-desc">Description</th>
      <th class="c-code">Supplier code</th>
      <th class="c-qty">Qty</th>
      <th class="c-uom">UOM</th>
      <th class="c-unit">Unit cost</th>
      <th class="c-total">Line total</th>
    </tr>
  </thead>
  <tbody>
    {% if lines and (lines|length) > 0 %}
      {% for line in lines %}
      <tr>
        <td class="c-desc"><div class="desc-main">{{ line.description or '—' }}</div></td>
        <td class="c-code">{{ line.supplier_product_code or '—' }}</td>
        <td class="c-qty">{{ '%.2f'|format(line.qty or 0) }}</td>
        <td class="c-uom">{{ line.uom or '—' }}</td>
        <td class="c-unit">£{{ '%.2f'|format(line.unit_cost_gbp or 0) }}</td>
        <td class="c-total">£{{ '%.2f'|format(line.line_total_gbp or 0) }}</td>
      </tr>
      {% endfor %}
    {% else %}
      <tr><td colspan="6" class="no-lines">No lines</td></tr>
    {% endif %}
  </tbody>
</table>

<div class="po-totals-wrap">
  <table class="po-totals" role="table" aria-label="Totals">
    <tbody>
      <tr><td>Subtotal</td><td>£{{ '%.2f'|format(po.subtotal_gbp or 0) }}</td></tr>
      <tr><td>VAT</td><td>£{{ '%.2f'|format(po.vat_gbp or 0) }}</td></tr>
      <tr class="grand"><td>Total</td><td>£{{ '%.2f'|format(po.total_gbp or 0) }}</td></tr>
    </tbody>
  </table>
</div>

<footer class="po-footer">
  Generated by Chartwell Press · Please quote PO number on all correspondence.
</footer>
"""

PO_TEMPLATE_CSS = """@page { size: A4; margin: 14mm; }
body {
  font-family: Arial, Helvetica, sans-serif;
  font-size: 12px;
  color: #111;
  margin: 0;
}
h1, h2, h3 { margin: 0; }

.po-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  gap: 18px;
  margin-bottom: 14px;
}
.po-header-left { flex: 1; }
.po-title { font-size: 20px; font-weight: 700; letter-spacing: 0.5px; }
.company { font-size: 14px; color: #555; margin-top: 2px; }
.po-header-right {
  min-width: 220px;
  border: 1px solid #ddd;
  padding: 10px 12px;
  border-radius: 8px;
  background: #fafafa;
}
.po-header-right div { margin: 2px 0; }

.po-addresses {
  display: flex;
  gap: 18px;
  margin-top: 14px;
}
.po-box {
  flex: 1;
  border: 1px solid #ddd;
  padding: 10px 12px;
  border-radius: 8px;
}
.po-box-title { font-weight: 700; margin-bottom: 6px; font-size: 12px; }
.muted { color: #666; font-size: 11px; }

.po-notes {
  margin-top: 14px;
  border: 1px solid #ddd;
  padding: 10px 12px;
  border-radius: 8px;
}
.po-notes .po-box-title { margin-bottom: 6px; }

.po-lines {
  width: 100%;
  border-collapse: collapse;
  margin-top: 14px;
  font-size: 12px;
  border: 1px solid #ddd;
}
.po-lines thead th {
  text-align: left;
  padding: 8px 10px;
  border-bottom: 2px solid #111;
  font-weight: 700;
  background: #f5f5f5;
}
.po-lines tbody td {
  padding: 8px 10px;
  border-bottom: 1px solid #eee;
  vertical-align: top;
}
.po-lines .c-qty,
.po-lines .c-unit,
.po-lines .c-total {
  text-align: right;
  white-space: nowrap;
}
.po-lines .c-code,
.po-lines .c-uom { white-space: nowrap; }
.po-lines .c-desc { width: 48%; }
.po-lines .c-code { width: 14%; }
.po-lines .c-qty { width: 8%; }
.po-lines .c-uom { width: 8%; }
.po-lines .c-unit { width: 11%; }
.po-lines .c-total { width: 11%; }
.po-lines .desc-main { font-weight: 600; }
.po-lines .no-lines { text-align: center; padding: 14px; color: #666; }

.po-totals-wrap {
  margin-top: 12px;
  display: flex;
  justify-content: flex-end;
}
.po-totals {
  width: 280px;
  border-collapse: collapse;
  font-size: 12px;
  border: 1px solid #ddd;
}
.po-totals td {
  padding: 6px 10px;
  border-bottom: 1px solid #eee;
}
.po-totals td:last-child {
  text-align: right;
  white-space: nowrap;
}
.po-totals .grand td {
  border-bottom: 2px solid #111;
  font-weight: 800;
  background: #f9f9f9;
}

.po-footer {
  margin-top: 18px;
  font-size: 11px;
  color: #666;
}
"""


def upgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        text("""
            UPDATE document_templates
            SET template_html = :body, template_css = :css
            WHERE doc_type = 'purchase_order'
        """),
        {"body": PO_TEMPLATE_BODY, "css": PO_TEMPLATE_CSS},
    )


def downgrade() -> None:
    pass
