"""Fix Jinja 'Unexpected end of template... innermost block is if' - consolidate notes block.

Revision ID: 023_po_fix_if
Revises: 022_po_a4_structured
Create Date: 2026-02-23

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import text

revision: str = "023_po_fix_if"
down_revision: Union[str, None] = "022_po_a4_structured"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Same layout as 022 but with notes block on single line to prevent TipTap/editor
# from splitting {% if %} and {% endif %} across block boundaries (causes Jinja error).
PO_TEMPLATE_BODY = """
<header class="po-header">
  <div class="po-header-left">
    <h1 class="po-title">Purchase Order</h1>
    <div class="company">Chartwell Press</div>
  </div>
  <div class="po-header-right">
    <div><strong>PO No:</strong> {{ po.po_number if po.po_number and not po.po_number.startswith('DRAFT-') else 'Draft' }}</div>
    <div><strong>Order date:</strong> {{ po.order_date.strftime('%d/%m/%Y') if po.order_date else '' }}</div>
    {% if po.required_by %}<div><strong>Required by:</strong> {{ po.required_by.strftime('%d/%m/%Y') }}</div>{% endif %}
    {% if po.expected_by %}<div><strong>Expected by:</strong> {{ po.expected_by.strftime('%d/%m/%Y') }}</div>{% endif %}
  </div>
</header>

<div class="po-addresses">
  <div class="po-box">
    <div class="po-box-title">Supplier</div>
    <div>{{ supplier.name if supplier else po.supplier_id }}</div>
    {% if supplier and supplier.address %}<div class="muted">{{ supplier.address }}</div>{% endif %}
    {% if supplier and supplier.city %}<div class="muted">{{ supplier.city }}</div>{% endif %}
    {% if supplier and supplier.postcode %}<div class="muted">{{ supplier.postcode }}</div>{% endif %}
    {% if supplier and supplier.country %}<div class="muted">{{ supplier.country }}</div>{% endif %}
    {% if supplier and supplier.email %}<div class="muted">{{ supplier.email }}</div>{% endif %}
    {% if supplier and supplier.phone %}<div class="muted">{{ supplier.phone }}</div>{% endif %}
  </div>
  <div class="po-box">
    <div class="po-box-title">Delivery</div>
    {% if po.delivery_name %}<div>{{ po.delivery_name }}</div>{% endif %}
    {% if po.delivery_address %}<div class="muted">{{ po.delivery_address }}</div>{% endif %}
  </div>
</div>

{% if po.notes %}<div class="po-notes"><div class="po-box-title">Notes</div><div>{{ po.notes }}</div></div>{% endif %}

<table class="po-lines" role="table" aria-label="Purchase order lines">
  <thead>
    <tr>
      <th class="c-desc">Description</th>
      <th class="c-code">Supplier code</th>
      <th class="c-qty">Qty</th>
      <th class="c-uom">UOM</th>
      <th class="c-unit">Unit cost</th>
      <th class="c-total">Line total</th>
    </tr>
  </thead>
  <tbody>
    {% if lines and (lines|length) > 0 %}
      {% for line in lines %}
      <tr>
        <td class="c-desc"><div class="desc-main">{{ line.description or '—' }}</div></td>
        <td class="c-code">{{ line.supplier_product_code or '—' }}</td>
        <td class="c-qty">{{ '%.2f'|format(line.qty or 0) }}</td>
        <td class="c-uom">{{ line.uom or '—' }}</td>
        <td class="c-unit">£{{ '%.2f'|format(line.unit_cost_gbp or 0) }}</td>
        <td class="c-total">£{{ '%.2f'|format(line.line_total_gbp or 0) }}</td>
      </tr>
      {% endfor %}
    {% else %}
      <tr><td colspan="6" class="no-lines">No lines</td></tr>
    {% endif %}
  </tbody>
</table>

<div class="po-totals-wrap">
  <table class="po-totals" role="table" aria-label="Totals">
    <tbody>
      <tr><td>Subtotal</td><td>£{{ '%.2f'|format(po.subtotal_gbp or 0) }}</td></tr>
      <tr><td>VAT</td><td>£{{ '%.2f'|format(po.vat_gbp or 0) }}</td></tr>
      <tr class="grand"><td>Total</td><td>£{{ '%.2f'|format(po.total_gbp or 0) }}</td></tr>
    </tbody>
  </table>
</div>

<footer class="po-footer">
  Generated by Chartwell Press · Please quote PO number on all correspondence.
</footer>
"""


def upgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        text("""
            UPDATE document_templates
            SET template_html = :body
            WHERE doc_type = 'purchase_order'
        """),
        {"body": PO_TEMPLATE_BODY},
    )


def downgrade() -> None:
    pass
