"""GOLD MASTER: Replace all purchase_order templates with editor-proof Jinja (no unclosed if/for).

Revision ID: 032_po_gold_master
Revises: 031_po_delivery_default
Create Date: 2026-02-24

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import text

revision: str = "032_po_gold_master"
down_revision: Union[str, None] = "031_po_delivery_default"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

GOLD_MASTER_HTML = """
<div class="po-page">

  <div class="po-header">
    <div class="po-company">
      <div class="po-title">Purchase Order</div>
      <div class="po-company-name">Chartwell Press</div>
    </div>

    <div class="po-meta">
      <div><strong>PO No:</strong> {{ po.po_number if po.po_number and not po.po_number.startswith('DRAFT-') else 'Draft' }}</div>
      <div><strong>Order date:</strong> {{ po.order_date.strftime('%d/%m/%Y') if po.order_date else '' }}</div>
      {% if po.required_by %}<div><strong>Required by:</strong> {{ po.required_by.strftime('%d/%m/%Y') }}</div>{% endif %}
      {% if po.expected_by %}<div><strong>Expected by:</strong> {{ po.expected_by.strftime('%d/%m/%Y') }}</div>{% endif %}
    </div>
  </div>

  <div class="po-addresses">
    <div class="po-address">
      <div class="label">Supplier</div>
      <div>{{ supplier.name if supplier else '' }}</div>
      {% if supplier and supplier.address %}<div>{{ supplier.address }}</div>{% endif %}
      {% if supplier and supplier.city %}<div>{{ supplier.city }}</div>{% endif %}
      {% if supplier and supplier.postcode %}<div>{{ supplier.postcode }}</div>{% endif %}
      {% if supplier and supplier.country %}<div>{{ supplier.country }}</div>{% endif %}
      {% if supplier and supplier.email %}<div>{{ supplier.email }}</div>{% endif %}
      {% if supplier and supplier.phone %}<div>{{ supplier.phone }}</div>{% endif %}
    </div>

    <div class="po-address">
      <div class="label">Deliver to</div>
      {% if po.delivery_name or po.delivery_address %}
        {% if po.delivery_name %}<div>{{ po.delivery_name }}</div>{% endif %}
        {% if po.delivery_address %}<div>{{ po.delivery_address }}</div>{% endif %}
      {% else %}
        <div>Chartwell Press</div>
        <div>171 Waterside Road</div>
        <div>Hamilton Industrial Park</div>
        <div>Leicester</div>
        <div>LE5 1TL</div>
        <div>United Kingdom</div>
      {% endif %}
    </div>
  </div>

  {% if po.notes %}<div class="po-notes"><strong>Notes</strong><div>{{ po.notes }}</div></div>{% endif %}

  <table class="po-lines">
    <thead>
      <tr>
        <th>Description</th>
        <th>Supplier code</th>
        <th class="right">Qty</th>
        <th>UOM</th>
        <th class="right">Unit cost</th>
        <th class="right">Line total</th>
      </tr>
    </thead>
    <tbody>
      {% if lines and (lines|length) > 0 %}
        {% for line in lines %}
          <tr>
            <td>{{ line.description or '—' }}</td>
            <td>{{ line.supplier_product_code or '—' }}</td>
            <td class="right">{{ '%.2f'|format(line.qty or 0) }}</td>
            <td>{{ line.uom or '—' }}</td>
            <td class="right">£{{ '%.2f'|format(line.unit_cost_gbp or 0) }}</td>
            <td class="right">£{{ '%.2f'|format(line.line_total_gbp or 0) }}</td>
          </tr>
        {% endfor %}
      {% else %}
        <tr><td colspan="6" class="center">No lines</td></tr>
      {% endif %}
    </tbody>
  </table>

  <div class="po-totals-wrap">
    <table class="po-totals">
      <tbody>
        <tr><td>Subtotal</td><td class="right">£{{ '%.2f'|format(po.subtotal_gbp or 0) }}</td></tr>
        <tr><td>VAT</td><td class="right">£{{ '%.2f'|format(po.vat_gbp or 0) }}</td></tr>
        <tr class="grand"><td>Total</td><td class="right">£{{ '%.2f'|format(po.total_gbp or 0) }}</td></tr>
      </tbody>
    </table>
  </div>

  <div class="po-footer">
    Generated by Chartwell Press · Please quote PO number on all correspondence.
  </div>

</div>
"""

GOLD_MASTER_CSS = """@page { size: A4; margin: 14mm; }
body { font-family: Arial, Helvetica, sans-serif; font-size: 12px; color: #111; }
.po-header { display:flex; justify-content:space-between; gap:16px; margin-bottom:14px; }
.po-title { font-size:20px; font-weight:800; }
.po-meta { text-align:right; }
.po-addresses { display:flex; gap:18px; margin:10px 0 14px; }
.po-address { width:50%; }
.label { font-weight:800; margin-bottom:4px; }
.po-notes { margin:8px 0 14px; padding:8px 10px; border:1px solid #ddd; border-radius:4px; }
.po-lines { width:100%; border-collapse:collapse; margin-top:8px; }
.po-lines th { text-align:left; padding:7px 8px; border-bottom:2px solid #111; font-weight:800; }
.po-lines td { padding:7px 8px; border-bottom:1px solid #ddd; vertical-align:top; }
.right { text-align:right; white-space:nowrap; }
.center { text-align:center; }
.po-totals-wrap { width:40%; margin-left:auto; margin-top:12px; }
.po-totals { width:100%; border-collapse:collapse; }
.po-totals td { padding:6px 8px; border-bottom:1px solid #ddd; }
.po-totals .grand td { font-weight:900; border-bottom:2px solid #111; }
.po-footer { margin-top:18px; font-size:11px; color:#666; }
"""


def upgrade() -> None:
    conn = op.get_bind()

    # Update ALL purchase_order templates with GOLD MASTER
    conn.execute(
        text("""
            UPDATE document_templates
            SET template_html = :html, template_css = :css
            WHERE doc_type = 'purchase_order'
        """),
        {"html": GOLD_MASTER_HTML.strip(), "css": GOLD_MASTER_CSS.strip()},
    )

    # Ensure exactly ONE is_active=true: keep most recently updated active, others false
    rows = conn.execute(
        text("""
            SELECT id, name, updated_at FROM document_templates
            WHERE doc_type = 'purchase_order'
            ORDER BY updated_at DESC NULLS LAST, created_at DESC NULLS LAST
        """)
    ).fetchall()

    if rows:
        # Deactivate all first
        conn.execute(
            text("""
                UPDATE document_templates SET is_active = false
                WHERE doc_type = 'purchase_order'
            """)
        )
        # Activate "Default Purchase Order" if exists, else first (most recent)
        default_row = next((r for r in rows if r[1] and "Default" in r[1]), rows[0])
        conn.execute(
            text("UPDATE document_templates SET is_active = true WHERE id = :tid"),
            {"tid": default_row[0]},
        )


def downgrade() -> None:
    pass
